server:
  port: 8080
spring:
  rabbitmq:
    host: 49.235.193.4
    port: 5672
    username: test
    password: test
    virtual-host: /
    #必须配置这个才会确认回调
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true
    listener:
      simple:
        retry:
          # 允许消息消费失败的重试
          enabled: true
          # 消息最多消费次数3次
          max-attempts: 3
          # 消息多次消费的间隔1秒
          initial-interval: 1000
        #  设置为false，会丢弃消息或者重新发布到死信队列
        default-requeue-rejected: false

